@startuml
class StarWars.Entities.Jedi {
- String lightsaberColor
- int forceLevel
- boolean isMaster
+ String getLightsaberColor()
+ int getForceLevel()
+ boolean isGrandMaster()
+ String toString()
+ String takeCare()
+ void setLightsaberColor(String)
+ void setForceLevel(int)
+ void setIsMaster(boolean)
+ void setModelType(String)
+ void setBatteryLevel(int)
+ void setCloneNumber(String)
+ void setFunction(String)
}




StarWars.Entities.Entity <|-- StarWars.Entities.Jedi
@enduml