@startuml
!include CloneTrooper.puml
!include Droid.puml
!include Jedi.puml
!include Sith.puml
!include Entity.puml
!include Main.puml
!include Menu.puml
!include EntityManager.puml

Main --> EntityManager
EntityManager "1" *-- "*" Entity
EntityManager --> Menu
@enduml